services:
  frontend:
    image: unsignedgodeveloper/chat-frontend:latest
    container_name: frontend_container
    restart: always
    ports:
      - "3000:4173"
    depends_on:
      - backend
      - nginx


  backend:
    image: unsignedgodeveloper/chat:latest
    container_name: chat_container
    restart: always
    ports:
      - "8080:8080"
    
  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
