name: Deploy Go Application

on:
    push:
        branches:
            - main
            - test

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Login to docker hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
            
            - name: Build docker image
              run: docker build -t unsignedgodeveloper/chat -f backend/Dockerfile .

            - name: Push image to docker hub
              run: docker push unsignedgodeveloper/chat:latest       
    build-frontend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Source
          uses: actions/checkout@v4
  
        - name: Login to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
  
        - name: Build Frontend Docker Image
          run: docker build -t unsignedgodeveloper/chat-frontend:latest -f frontend/Dockerfile .
  
        - name: Push Frontend Image to Docker Hub
          run: docker push unsignedgodeveloper/chat-frontend:latest
            

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
          - name: Pull docker image
            run: docker-compose pull
          
          - name: Delete old container
            run: docker-compose down

          - name: Run docker container
            run: docker-compose up -d

          